research/config/routes.rb
ActionController::Routing::Routes.draw do |map|

  map.courses_json '/courses/json', :controller => 'courses', :action => 'json' 
  map.categories_json '/categories/json', :controller => 'categories', :action => 'json'
  map.proglangs_json '/proglangs/json', :controller => 'proglangs', :action => 'json' 

  map.resources :pictures

  map.activate_job      '/jobs/activate/:id',         :controller => 'jobs',    :action => 'activate'
  map.new_job_applic    '/jobs/:job_id/apply',        :controller => 'applics', :action => 'new'
  map.create_job_applic '/jobs/:job_id/doapply',      :controller => 'applics', :action => 'create', :method => 'post'
  map.list_jobs_applics '/jobs/:job_id/applications', :controller => 'applics', :action => 'index'
  map.applic            '/applications/:id',          :controller => 'applics', :action => 'show'
  map.destroy_applic    '/applications/:id/withdraw', :controller => 'applics', :action => 'destroy'
  map.applic_resume     '/applications/:id/resume',   :controller => 'applics', :action => 'resume'
  map.applic_transcript '/applications/:id/transcript', :controller=>'applics', :action => 'transcript'
  map.job_search        '/search',                    :controller => 'jobs',    :action => 'index'
  map.resources :jobs   # Must be last so the above routes take precedence

  map.resources :reviews

  map.resources :categories 

  map.resources :documents

  map.logout '/logout', :controller => 'sessions', :action => 'destroy'
  map.login '/login', :controller => 'sessions', :action => 'new'
  map.register '/register', :controller => 'users', :action => 'create'
  map.signup '/signup', :controller => 'users', :action => 'new'
  
  map.resources :users
  
  map.resource :session

  map.dashboard '/dashboard', :controller => :dashboard, :action => :index

  

  
  map.root :controller => "home"
  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

research/app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :jobs
  
  has_many :interests
  has_many :users, :through => :interests
  
end

research/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def json
        cats = Category.find(:all)
        cats = cats.collect { |cat| cat.name }

        respond_to do |format|
            format.json { render :json => cats }
        end

    end

end

research/app/helpers/categories_helper.rb
module CategoriesHelper
end

research/app/views/categories/edit.html.erb
<h1>Editing category</h1>

<% form_for(@category) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :job_ids %><br />
    <%= f.text_field :job_ids %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

research/app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Job</th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%=h category.name %></td>
    <td><%=h category.jobs %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New category', new_category_path %>

research/app/views/categories/new.html.erb
<h1>New category</h1>

<% form_for(@category) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :job_ids %><br />
    <%= f.text_field :job_ids %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', categories_path %>

research/app/views/categories/show.html.erb
<p>
  <b>Name:</b>
  <%=h @category.name %>
</p>

<p>
  <b>Job:</b>
  <%=h @category.jobs %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>